name: Build

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    name: Release ${{ matrix.target }}
    runs-on: windows-latest
    
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          #- i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Build
        uses: actions-rs/cargo@v1
        
      - name: Create/Update Release with latest PDFs
        uses: ncipollo/release-action@v1
        with:
          #use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}
          tag: latest
          name: "Latest Build (${{ github.event.repository.updated_at }})"
          artifacts: |
            target/release/*.exe
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
